development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://ugjngrcyubyxno:1b893c2745a4a8dee27324a52a61804fbe0edb80bd7c6fa88f50464d8718b733@ec2-54-204-18-53.compute-1.amazonaws.com:5432/d5javkcim1j520
  channel_prefix: beasts_of_berlin_production
